{
 "title": "Vertx-Application(cluster-instance)",
 "time": { "from": "2021-04-19T09:50:10.000Z", "to": "2021-04-19T12:00:04.000Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Application",
    "query": "label_values(kubernetes_namespace)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{kubernetes_namespace=\"$cluster\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Quick facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No. of  Instances up in cluster : $cluster ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{kubernetes_namespace=\"$cluster\"})"
    },
    {}
   ]
  },
  {
   "title": "Process Current  CPU Usage : $instance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{kubernetes_pod_name=\"$instance\"} ",
     "legendFormat": " ",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Non-Heap used : $instance  ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_pod_name=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{kubernetes_pod_name=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": " Heap used :  $instance ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_pod_name=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{kubernetes_pod_name=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "JVM Memory per instance : $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": " JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_pod_name=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{kubernetes_pod_name=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{kubernetes_pod_name=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": " JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_pod_name=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{kubernetes_pod_name=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{kubernetes_pod_name=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": " JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Misc per instance : $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": " CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{kubernetes_pod_name=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{kubernetes_pod_name=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{kubernetes_pod_name=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{kubernetes_pod_name=\"$instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{kubernetes_pod_name=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{kubernetes_pod_name=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{kubernetes_pod_name=\"$instance\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{kubernetes_pod_name=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "HTTP Metrics per instance:  $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vertx_http_server_connections{kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$instance\"}) "
    }
   ]
  },
  {
   "title": "Response time by code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}[1m])) by (code) / sum(irate(vertx_http_server_responseTime_seconds_count{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}[1m])) by (code)",
     "legendFormat": "{{code}} 1 m instant"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le,path))",
     "legendFormat": "{{code}} [med]"
    }
   ]
  },
  {
   "title": "Request count rate by code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requestCount_total{kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$instance\"}[1m])) by (code), 0.001)"
    }
   ]
  },
  {
   "title": "Response time/latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum{kuberenetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}[1m])) / sum(irate(vertx_http_server_responseTime_seconds_count{kuberenetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}[1m]))",
     "legendFormat": "1 minute  instant latency"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_responseTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_responseTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "[99p]"
    },
    {
     "expr": "sum(rate(vertx_http_server_responseTime_seconds_sum{cluster=\"$cluster\", instance=\"$instance\"}[1m])) /sum(rate(vertx_http_server_responseTime_seconds_count{cluster=\"$cluster\", instance=\"$instance\"}[1m]))",
     "legendFormat": "1 minute avg latency "
    }
   ]
  },
  {
   "title": "Throughput ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_responseTime_seconds_count{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\",code=\"200\"}[1m])) /sum(rate(vertx_http_server_responseTime_seconds_sum{kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$instance\",code=\"200\"} [1m])) ",
     "legendFormat": "{{code}} 1miniute avg "
    },
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_count{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\", code=\"200\"}[1m]))  by (path) /sum(irate(vertx_http_server_responseTime_seconds_sum{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\",code=\"200\"} [1m])) by (path) ",
     "legendFormat": "{{code}} 1minute instant "
    }
   ]
  },
  {
   "title": "Total HTTP Server bytes sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesSent_sum{kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$instance\"}[1m])) / sum(rate(vertx_http_server_bytesSent_count{kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$instance\"}[1m]))",
     "legendFormat": "[avg]"
    }
   ]
  },
  {
   "title": "Total  HTTP Server bytes received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesReceived_sum{kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$instance\"}[1m])) / sum(rate(vertx_http_server_bytesReceived_count{kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$instance\"}[1m]))",
     "legendFormat": "[avg]"
    }
   ]
  },
  {
   "title": "Event Bus Metrics per instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "Eventbus: handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vertx_eventbus_handlers{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}) by (address)",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vertx_eventbus_pending{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}) by (address)",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Eventbus: total sent rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_sent_total{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total{cluster=\"$cluster\", instance=\"$instance\"}[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total{cluster=\"$cluster\", instance=\"$instance\"}[5m])) ",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus: total received rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_received_total {kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total{cluster=\"$cluster\", instance=\"$instance\"}[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total{cluster=\"$cluster\", instance=\"$instance\"}[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus : processing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}[1m])) / sum(irate(vertx_eventbus_processingTime_seconds_count{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Eventbus: processing time by address",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}[1m])) by (address) / sum(irate(vertx_eventbus_processingTime_seconds_count{kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$instance\"}[1m])) by (address)",
     "legendFormat": "{{address}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le,address))",
     "legendFormat": "{{address}} [med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le, address))",
     "legendFormat": "{{address}} [95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le,address))",
     "legendFormat": "{{address}} [99p]"
    }
   ]
  }
 ]
}