# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
version: "3"

networks:
  analytics-net:
    external: true

services:
  kudu-master:
    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
    container_name: kudu-master
    ports:
      - "7051:7051"
      - "8051:8051"
    command: ["master"]
    volumes:
      - kudu-master:/var/lib/kudu
    networks:
      - analytics-net
    environment:
      - KUDU_MASTERS=kudu-master:7051
      # TODO: Use `host.docker.internal` instead of KUDU_QUICKSTART_IP when it
      # works on Linux (https://github.com/docker/for-linux/issues/264)
      - >
        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
        --rpc_bind_addresses=kudu-master:7051
        --rpc_advertised_addresses=kudu-master:7051
        --webserver_port=8051
        --webserver_advertised_addresses=kudu-master:8051
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false
    restart: always
  kudu-tserver:
    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
    container_name: kudu-tserver
    depends_on:
      - kudu-master
    ports:
      - "7050:7050"
      - "8050:8050"
    command: ["tserver"]
    volumes:
      - kudu-tserver:/var/lib/kudu
    networks:
      - analytics-net
    environment:
      - KUDU_MASTERS=kudu-master:7051
      - >
        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
        --rpc_bind_addresses=kudu-tserver:7050
        --rpc_advertised_addresses=kudu-tserver:7050
        --webserver_port=8050
        --webserver_advertised_addresses=kudu-tserver:8050
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false
    restart: always
volumes:
  kudu-master:
  kudu-tserver:
