apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: adaptor-framework
  labels:
    type: minio-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "ebs-storage-class"
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: minio-pv

