apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: adaptor-framework
  labels:
    type: minio-pv
spec:
  capacity:
    storage: 10Gi
  storageClassName: "ebs-storage-class"
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
        volumeID: "vol-0c34805a68ccbbdbf"
        fsType: ext4
