apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio-service
  namespace: adaptor-framework
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30005
  selector:
    # Looks for labels `app:minio1` in the namespace and applies the spec
    app: minio
