version: '3.7'

networks:
  adaptor-net:
    external: true

services:

  jobmanager:
    # image: flink:1.12.2-scala_2.12-java11
    build: 
      dockerfile: ./Dockerfile
      context: .
    hostname: jobmanager
    ports:
      - 8081:8081
      - 9251:9251
    expose:
      - "9251"
    env_file:
      - ./env
    environment:
      - "TZ=Asia/Kolkata"
    networks:
      - adaptor-net
    command: "jobmanager"
    volumes:
      - ./flink-jobmanager/log4j-console.properties:/opt/flink/conf/log4j-console.properties
    restart: always
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"


  taskmanager:
    # image: flink:1.12.2-scala_2.12-java11 
    build: 
      dockerfile: ./Dockerfile
      context: .
    hostname: taskmanager
    volumes:
      - ./flink-taskmanager/log4j-console.properties:/opt/flink/conf/log4j-console.properties
    ports:
      - 9252:9251
    expose:
      - "9251"
    env_file:
      - ./env
    environment:
      - "TZ=Asia/Kolkata"
    networks:
      - adaptor-net
    command: "taskmanager"
    restart: always
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

## TODO: REMOVE VOLUME
volumes:
  jars:
