version: '3.7'

networks:
  analytics-net:
    external: true

services:

  jobmanager:
    # image: flink:1.12.2-scala_2.12-java11
    build: 
      dockerfile: ./Dockerfile
      context: .
    hostname: jobmanager
    ports:
      - 8081:8081
    env_file:
      - ./env
    networks:
      - analytics-net
    command: "jobmanager"
    volumes:
      - ./jars:/jars
    restart: always


  taskmanager:
    # image: flink:1.12.2-scala_2.12-java11 
    build: 
      dockerfile: ./Dockerfile
      context: .
    hostname: taskmanager
    env_file:
      - ./env
    networks:
      - analytics-net
    command: "taskmanager"
    restart: always

volumes:
  jars:
