version: '3.7'

networks:
  adaptor-net:
    external: true

services:

  jobmanager:
    build: 
      dockerfile: ./Dockerfile
      context: .
    hostname: jobmanager
    ports:
      - 8081:8081
    env_file:
      - ./env
    networks:
      - adaptor-net
    command: "jobmanager"


  taskmanager:
    build: 
      dockerfile: ./Dockerfile
      context: .
    hostname: taskmanager
    env_file:
      - ./env
    networks:
      - adaptor-net
    command: "taskmanager"

