version: "3.7"

networks:
  adaptor-net:
    external: true

volumes:
  zkdata:
  zkdatalog:

services:
  zook:
    image: zookeeper:3.4.9
    container_name: zook
    hostname: zook
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zook:2888:3888
    volumes:
      - zkdata:/data
      - zkdatalog:/datalog
    networks: 
      - adaptor-net
    restart: always
