version: '3.7'

networks:
  adaptor-net:
    driver: bridge


services:

  mockserver:
    image: iudx/adaptor-mockserver:latest
    ports:
      - "8080:8080"
    networks: 
      - adaptor-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"

