apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace}}
  name: {{ .Values.loki.service.name}}-headless
  {{- with .Values.loki.labels }}
  labels:
    {{- toYaml .  | nindent 4 }}
  {{- end}}
  {{- with .Values.loki.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}

spec:
  clusterIP: None
  ports:
    - port: 3100
      protocol: TCP
      name: {{ .Values.loki.container.port}}
      targetPort: {{ .Values.loki.container.port}}
  selector:
    app: loki
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loki.service.name}}
  namespace: {{ .Values.global.namespace }}
  {{- with .Values.loki.labels }}
  labels:
    {{- toYaml .  | nindent 4 }}
  {{- end}}  
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
spec:
  type: {{ .Values.loki.service.type}}
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: {{ .Values.loki.labels.app }}
