apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
  namespace: adaptor-framework
data:
  config.json: |
    {
      "version": "1.0",
      "modules": [
        {
          "id": "in.org.iudx.adaptor.server.Server",
          "ssl": false,
          "port": 8080,
          "ip": "127.0.0.1",
          "keystorePath": "./configs/keystore.jks",
          "keystorePassword": "password",
          "verticleInstances": 1,
          "jarOutPath": "./upload-jar",
          "quartzPropertiesPath": "./configs/quartz.properties",
          "adminAuth": {
            "username": "admin",
            "password": "admin"
          }
          "rmqHost": "rmq-rabbitmq",
          "rmqMgmtPort": 15672,
          "rmqPort": 5672,
          "rmqVhost": "%2F",
          "rmqUsername": "guest",
          "rmqPassword": "guest"
        },
        {
          "id": "in.org.iudx.adaptor.server.flink.FlinkClientVerticle",
          "verticleInstances": 1,
          "flinkOptions": {
            "port": 8081,
            "host": "flink-cluster-rest",
            "ssl": false,
            "timeout": 10000
          }
        },
        {
          "id": "in.org.iudx.adaptor.server.codegeninit.CodegenInitVerticle",
          "templatePath": "./template",
          "jarOutPath": "./upload-jar",
          "verticleInstances": 1
        },
        {
          "id": "in.org.iudx.adaptor.server.database.DatabaseVerticle",
          "verticleInstances": 1,
          "databaseUser": "root",
          "databasePassword": "adaptor@db",
          "databseHost": "postgressvc.adaptor-framework.svc.cluster.local",
          "databasePort": 5432,
          "databaseName": "iudx-adaptor",
          "databasePoolSize": 5
        }
      ]
    }
  
  quartz.properties: |
    org.quartz.scheduler.instanceName = FLinkQuartzScheduler
    org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
    org.quartz.threadPool.threadCount = 5

    org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
    org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
    org.quartz.jobStore.dataSource = quartzDS

    org.quartz.dataSource.quartzDS.driver = org.postgresql.Driver
    org.quartz.dataSource.quartzDS.URL = jdbc:postgresql://postgressvc.adaptor-framework.svc.cluster.local:5432/iudx-adaptor
    org.quartz.dataSource.quartzDS.user = root
    org.quartz.dataSource.quartzDS.password = adaptor@db
