server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: flink-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: flink_container
      __path__: /var/lib/docker/containers/*/*-json.log

  pipeline_stages:
  - match:
      selector: '{filename="/var/lib/docker/containers/*/*-json.log"}'
      stages:
      - labels:
          host: flink-node
  - json:
      expressions:
        log: log
        stream: stream
        docker_time: time
        container_info: attrs.tag
  - json:
      expressions:
        time: timeMillis
        source: source
        sourceUrl: sourceURL
        level: level
        origin: loggerName #class from which its logged
        message: message
  - labels:
      source:
      sourceUrl:
      #level:        # level will create more streams, 5x times
      #origin:
  - output:
      source: log

  - timestamp:
      source: docker_time
      format: RFC3339

