server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push


scrape_configs:

- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:

  - json:
      expressions:
        output: log
        stream: stream
        attrs: attrs
        tag: attrs.tag
        time: time

  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: tag
  - labels:
      image_name:
      container_name:
      image_id:
      container_id:

  - regex:
      expression: (?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})? ?\[?(?P<level>.*?)\]? (?P<context>.*?) \[(?P<adaptor_id>.*?)\] - (\[(event_key - )(?P<event_key>.*?)\])? ?-? ?(\[(status_code - )(?P<status_code>\d{3})\])? ?-? ?(\[(summary - )(?P<http_error_summary>.*?)\])?-?(?P<message>(?s:.*))$
      source: output
  - labels:
      context:
      adaptor_id:
      level:
      stream:
      tag:
      status_code:
      http_error_summary:
      message:
      event_key:

  - timestamp:
      format: RFC3339Nano
      source: time

  - output:
      source: output