apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeExporter.name }}
  namespace: {{ .Values.global.namespace}}
  labels:
    name: {{ .Values.nodeExporter.labels.name }}
spec:
  type: {{ .Values.nodeExporter.service.type }}
  ports:
    - port: {{ .Values.nodeExporter.service.port }}
      targetPort: {{ .Values.nodeExporter.ports.number }}
      protocol: TCP
  selector:
    name: {{ .Values.nodeExporter.name }}
