apiVersion: v1
kind: Service
metadata:
  name: postgressvc
  namespace: adaptor-framework
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres