config:
  table_manager:
    retention_deletes_enabled: true
    retention_period: 72h

  query_scheduler:
    max_outstanding_requests_per_tenant: 2048

  query_range:
    parallelise_shardable_queries: false
    split_queries_by_interval: 0

service:
  type: ClusterIP
  nodePort:
  port: 3100
  annotations: {}
  labels: {}
  targetPort: http-metrics

nodeSelector:
  node.kubernetes.io/instance-type: t3.medium

resources:
  limits:
   cpu: 1800m
   memory: 3.8Gi
  requests:
   cpu: 1500m
   memory: 3.5Gi

persistence:
  enabled: true
  accessModes:
  - ReadWriteOnce
  size: 60Gi
  storageClassName: "ebs-storage-class"
  annotations:
  volumeBindingMode: "WaitForFirstConsumer"
  reclaimPolicy: "Delete"