---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
- flink.rules.yml

scrape_configs:
- job_name: 'flink'
  static_configs:
  - targets: ['docker_taskmanager_1:9249', 'docker_jobmanager_1:9249']
  - labels:
      name: flink_taskmanager_job_task_operator_value_histogram 
