---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
- flink.rules.yml

scrape_configs:
- job_name: 'flink'
  static_configs:
  - targets: ['172.17.0.1:9251', '172.17.0.1:9252']
  - labels:
      name: flink_taskmanager_job_task_operator_value_histogram 
