version: '3.7'

networks:
  adaptor-net:
    external: true

services:
  server:
    image: iudx/adaptor-server:latest
    ports:
      - "8080:8080"
    networks: 
      - adaptor-net
    volumes:
      - ../../configs/:/usr/share/app/iudx-adaptor-framework/configs/
    environment:
      - M2_HOME=/usr/share/maven/
    command: "java -jar server/target/server.jar -c configs/config.json -Dmaven.home=/root/.m2"
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
