apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.service.name }}
  namespace: {{ .Values.namespace}}
  {{- with .Values.grafana.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.ports.port }}
#      targetPort: {{ .Values.grafana.ports.number }}
      nodePort: {{ .Values.grafana.service.port }}
      name: 
  {{- with .Values.grafana.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    
