@startuml

[*] --> GenericSourceFunction: From DataSource
GenericSourceFunction: Load state (connection/auth info, etc)
GenericSourceFunction: Watermark with timestamp

GenericSourceFunction --> GenericProcessFunction
GenericProcessFunction: Load state (last processed packetInfo, etc)
GenericProcessFunction: De-Deduplicate
GenericProcessFunction: Transform
GenericProcessFunction: Process
GenericProcessFunction: Aggregate


GenericProcessFunction --> GenericSinkFunction
GenericSinkFunction: Load state (connection/auth info, etc)
GenericSinkFunction: Publish to sink

@enduml
