@startuml
class ApiConfig  {
  -- public (stateful) --
  Map headers
  String body
  String url
  String requestType // get,post
  String headerString
  -- public --
  Object getMessage()
  void setApi(String api)
  void setBody(String body)
  void setHeader(String key, String value)
  void setHeaders(Multimap headers)
}
@enduml

