@startuml
class ApiConfig {
    <implements SourceConfig>
  -- public (stateful) --
  Map headers
  String body
  String url
  String requestType // get,post
  String headerString
  long pollingInterval
  Transformer transformer
  -- public --
  Object getMessage()
  ApiConfig setBody(String body)
  ApiConfig setHeader(String key, String value)
  ApiConfig setHeaders(Multimap headers)
  ApiConfig setPollingInterval(long pollingInterval)
}
@enduml
