@startuml
class GenericProcessFunction  {
    <extends KeyedProcessFunction>
  -- public --
  ApiConfig apiconfig
  Transformer transform // Json-to-json
  Deduplicator deduplicate
  Aggregater aggregate
  -- private (stateful) --
  State state
  -- public --
  void open()
  void onTimer()
  processElement(Message msg, ...)
}
@enduml

