@startuml

[*] --> Init : onMessage

State --> Init : Retreive stored state

Init --> Deduplicate : Includes late arrival filter

Deduplicate --> ProcessElement

ProcessElement --> State : Update state
ProcessElement --> Schedule : Optional for batching
ProcessElement --> SinkFunction : Without batching
Schedule --> SinkFunction

@enduml
