@startuml
class GenericProcessFunction  {
    <extends KeyedProcessFunction>
  -- public --
  Transformer transform // Json-to-json
  Aggregater aggregate
  -- private (stateful) --
  State state
  -- public --
  void open()
  void onTimer()
  <T> processElement(<T>)
  -- private --
  void deduplicate()
  void transform()
  void aggregate()
}
@enduml

