@startuml

[*] --> Init : onMessage

State --> Init : Retreive stored state

Init --> Deduplicate : Includes late arrival filter

Deduplicate --> ProcessElement : Transform

ProcessElement --> State : Update state
ProcessElement --> Schedule : Optional for batching
ProcessElement --> Emit : to next stage without batching

@enduml
