@startuml
class GenericJsonMessage  {
    <implements Serializable>
  -- public (stateful) --
  String body
  optional JSONObject jsonBody
  optional JSONArray jsonBody
  String key
  String responseHeaders
  Instance timestamp
  int statusCode
  -- public --
  long getEventTime()
  GenericJsonMessage setEventTime()
  GenericJsonMessage setKey(String key)
  GenericJsonMessage setResponseBody(String body)
  GenericJsonMessage setResponseStatusCode()
  int getResponseHeaders()
  Object getResponseBody()
  HashMap<String,String> getResponseHeaders()

}
@enduml

