@startuml
class HttpEntity  {
    <implements Serializable>
  -- public (stateful) --
  -- private --
  ApiConfig apiConfig
  Parser<PO> parser
  HttpClient httpClient
  HttpRequest httpRequest
  -- public --
  String getSerializedMessage()
  Message getMessage()
  HttpEntity setParser(Parser<PO> parser)
  HttpEntity setApiConfig(ApiConfig api)
  ApiConfig getApiConfig()
  
}
@enduml

