@startuml

[*] --> Init
Init: Get APIConfig
Init: Init HttpEntity

Init --> Sleep

Sleep --> Process : timerEvent
Process : onEvent(), \n annotate time, add watermark

Process --> Emit
Emit : collectWithTimestamp()

Emit --> Sleep : processComplete

@enduml
