@startuml
class HTTPSource  {
    <extends SourceFunction>
  -- public (stateful) --
  Object api
  Object token
  Object schedule
  DateTime lastPacketTime
  -- private (stateful) --
  Timer timer
  DateTime nextTime
  Object data
  -- public --
  void run()
  void open()
  void close()
  void onEvent()
  void schedule()
  String addWatermark(DateTime packetTime)
  -- private --
  void cancelNext()
  void cancel()
  void scheduleNext()
}
@enduml

