@startuml
class HttpEntity  {
    <implements Serializable>
  -- public (stateful) --
  -- private --
  ApiConfig apiConfig
  HttpClient httpClient
  HttpRequest httpRequest
  -- public --
  String getSerializedMessage()
  GenericJsonResponse getResponse()
  HttpEntity setApi(Api api)
  Api getApi(Api api)
}
@enduml

