@startuml
interface Parser  {
    <extends SerializationSchema>
  -- public methods --
  String getKey()
  String getTimeIndex()
  Message parse(String message)
  Parser initialize()
  byte[] serialize(Message body)
}
@enduml
