kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loki-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  labels:
    app: loki-deployment
spec:
  selector:
    matchLabels:
      app: loki-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: loki-pod
    spec:
      containers:
        - name: loki-container
          image: grafana/loki:2.4.0
          args:
            - --config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-conf
              mountPath: /etc/loki
            - name: loki-data
              mountPath: /data/loki
      volumes:
        - name: loki-conf
          configMap:
            name: loki-conf
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-pvc
