apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-deployment
  namespace: adaptor-framework
  labels:
    app: rmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmq
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
        - name: rmq
          image: rabbitmq:3-management
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
          volumeMounts:
            - mountPath: /etc/rabbitmq/definitions.json
              name: rmq-volume
          ports:
            - containerPort: 5672
            - containerPort: 15672
      volumes:
        - name: rmq-volume
          hostPath:
            path: /home/krithik/Desktop/Git/iudx-adaptor-framework/setup/rmq/mock-rmq.json
            type: File
