apiVersion: v1
kind: Service
metadata:
  name: adaptor-framework-ui
  namespace: adaptor-framework
  labels:
    app: adaptor-framework-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: adaptor-framework-ui
