{
 "title": "Rules Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job_name", "label": "Job Name", "query": { "query": "label_values(job_name)" } },
   { "name": "task_number", "label": "Task Number", "query": { "query": "label_values(task_attempt_num)" } },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Data Counter",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_RuleFunctionElementCounter{task_attempt_num=~\"$task_number\",job_name=~\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Rule Counter",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_RuleFunctionRuleCounter{task_attempt_num=~\"$task_number\",job_name=~\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Rule Alert Counter",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_RuleFunctionAlertCounter{task_attempt_num=~\"$task_number\",job_name=~\"$job_name\"}"
    }
   ]
  },
  {
   "title": "RMQ Sink Counter",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_RMQSinkCounter{task_attempt_num=~\"$task_number\",job_name=~\"$job_name\"}"
    }
   ]
  },
  {
   "title": "numRecordsInPerSecond",
   "type": "graph",
   "description": "umRecordsInPerSecond",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsInPerSecond"
    }
   ]
  },
  {
   "title": "numRecordsOutPerSecond",
   "type": "graph",
   "description": "numRecordsOutPerSecond",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsOutPerSecond"
    }
   ]
  },
  {
   "title": "numberOfFailedCheckpoints",
   "type": "graph",
   "description": "numberOfFailedCheckpoints",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_jobmanager_job_numberOfFailedCheckpoints{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{host}}_{{job_name}}_FailedCheckpoints"
    }
   ]
  },
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({adaptor_id=\"$job_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({adaptor_id=\"$job_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "{adaptor_id=\"$job_name\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({adaptor_id=\"$job_name\"})[$__interval])) by (stream)"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" donut",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({adaptor_id=\"$job_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (pod_name)"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({adaptor_id=\"$job_name\"})[$__interval])) by (stream)"
    }
   ]
  }
 ]
}