apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-conf
data:
  promtail.yaml: |
    server:
      http_listen_address: 0.0.0.0
      http_listen_port: 9080

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-svc.monitoring.svc.cluster.local:3100/loki/api/v1/push


    scrape_configs:
      - job_name: kubernetes-pods-app
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: default
