apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail-daemonset
  labels:
    app: promtail-daemonset
spec:
  selector:
    matchLabels:
      app: promtail-pod
  template:
    metadata:
      labels:
        app: promtail-pod
    spec:
      hostNetwork: true
      serviceAccountName: promtail-serviceaccount
      containers:
        - name: promtail-container
          image: grafana/promtail:2.0.0
          args:
            - --config.file=/etc/promtail/promtail.yaml
          ports:
            - containerPort: 9080
              name: http
          volumeMounts:
            - name: promtail-conf
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
            - name: secret-volume
              mountPath: /var/run/secrets
            - name: run
              mountPath: /run/promtail
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: promtail-conf
          configMap:
            name: promtail-conf
        - name: varlog
          hostPath:
            path: /var/log
        - name: secret-volume
          hostPath:
            path: /var/run/secrets
        - name: run
          hostPath:
            path: /run/promtail
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
